Resolve conflicts between danbone/issue_143_icache on PR #152 and branch master
riscv-software-src/riscv-perf-model pull request #211
Opened 2024-09-26 17:48 UTC by dragon540

2024-09-29 14:20 UTC, klingaard commented
:thinking:  Shobhit, how did you do the merge?  There shouldn't be this many files changed...

2024-09-29 20:53 UTC, dragon540 commented
@klingaard, I have mistakenly committed .idea and cmake-debug too, removing them should decrease the number of files changed to ~45 files. To do the merge, I copied the branch on PR #152 under my name, and merged master branch into it after resolving conflicts.

2024-10-01 01:01 UTC, jeffnye-gh requested changes
please remove the clion (.idea etc) and .cmake files from this PR and push again
also the cmake-build-debug/CMakeCache.txt cache files should not be part of the PR. I assume these are also part of clion.

you should consider adding these files to the toplevel .gitignore for future

2024-10-01 02:40 UTC, jeffnye-gh commented
@Shobhit. I have a question, looking at Dans code the dcache operates on credits. This merge seems to revert to acks in the dcache, is this correct? and is it intentional?  

sparta::DataInPort<uint32_t> in_l2cache_credits_
vs.
sparta::DataInPort<uint32_t> in_l2cache_ack_

2024-10-01 07:23 UTC, dragon540 commented
removed extra files and folders (.idea, cmake-build-debug, etc) from the PR

2024-10-21 04:24 UTC, jeffnye-gh requested changes
Minor changes requested, remove some generated files.

2024-10-21 13:40 UTC, dragon540 commented on test/core/l2cache/Testing/Temporary/LastTest.log
> +----------------------------------------------------------
Removed generated log files

2024-10-21 13:40 UTC, dragon540 commented
Removed generated log files

2024-10-28 22:07 UTC, jeffnye-gh approved these changes

2024-10-30 16:53 UTC, klingaard commented on stf_lib
Did you intend to update stflib?

2024-10-30 16:54 UTC, klingaard approved these changes
This is good work.  Before merging, I'd like to make sure moving stflib was intended.

2024-10-31 01:07 UTC, dragon540 commented
I was facing some issues with the version of stflib which was there in dan's PR, therefore updated it. However, the version of stflib which is in upstream branch works too. I have updated the stflib submodule to keep it consistent with the present version in olympia.

2024-10-31 14:21 UTC, merged