Adding Support: Configurable Cache Replacement Policies
riscv-software-src/riscv-perf-model pull request #230
Opened 2024-11-24 18:04 UTC by govardhnn

Building on [Issue#61](https://github.com/riscv-software-src/riscv-perf-model/issues/61), this merge request proposes to add configurable cache-replacement policies to Olympia.

2025-01-13 17:11 UTC, knute-mips commented
@govardhnn Can you add the missing files that are preventing CI from running?

2025-01-17 08:22 UTC, govardhnn commented
Will fix this by the Monday(Jan 20) TG meeting. Apologies for the delayed response!

2025-01-17 13:45 UTC, govardhnn commented
Hi, I have borrowed the missing `cache/` files from Sparta, which I implicitly assumed would be picked up form Map for the includes.
Not sure if this is right, but the regress target works in the `release/` directory locally 
- `make -j4 regress`  
```
  100% tests passed, 0 tests failed out of 102
  
  Total Test time (real) =  40.33 sec
  [100%] Built target regress
```

2025-01-17 17:45 UTC, klingaard commented
You are correct that the missing cache files should be picked up from the sparta install.  I cloned your branch locally, removed the `core/cache` directory and olympia built cleanly for me.

2025-01-18 06:09 UTC, govardhnn commented
Yep @knute-mips, I'll try to replicate the same commands from `Ubuntu-Release-gcc` to see if the issue is in the CI.
Meanwhile let me also look into other areas to contribute in Olympia.

2025-01-20 17:16 UTC, govardhnn commented
@knute-mips looks like the Branch-Pedictor test `BranchPred_test_Run` seg-faulted. Can you please rerun the CI tests? 
I could not join the meeting today, apologies.

``` 
99% tests passed, 1 tests failed out of 109

Total Test time (real) =  80.96 sec

The following tests FAILED:
	 90 - BranchPred_test_Run (SEGFAULT)
Errors while running CTest
Output from these tests are in: /home/runner/work/riscv-perf-model/riscv-perf-model/Release/test/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make[3]: *** [test/CMakeFiles/regress.dir/build.make:70: regress] Error 8
make[2]: *** [CMakeFiles/Makefile2:2171: test/CMakeFiles/regress.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2178: test/CMakeFiles/regress.dir/rule] Error 2
make: *** [Makefile:839: regress] Error 2
+ BUILD_OLYMPIA=2
+ '[' 2 -ne 0 ']'
+ echo 'ERROR: build/regress of olympia FAILED!!!'
+ exit 1
ERROR: build/regress of olympia FAILED!!!
```

2025-03-10 16:57 UTC, govardhnn commented
Hi @klingaard can you please approve the workflow? I am unable to trigger the GitHub CI regressions.
I have bumped the sparta v2 version to the latest.
![image](https://github.com/user-attachments/assets/eb699771-d7ba-4c33-94be-52d8e05d09c1)

2025-03-11 03:09 UTC, govardhnn commented
@klingaard the CI has passed. Please review and merge at your convenience.

2025-03-11 21:17 UTC, klingaard requested changes
This looks good.  Do you plan on adding testing?

Also, you are out of sync with mavis and fsl subrepos.  I believe you're replacing them in your PR with older revisions.  Please fix that.

2025-03-13 03:21 UTC, govardhnn commented on .github/actions/build/entrypoint.sh
> +make -j$NUM_CORES VERBOSITY=1 regress
Updated this flag, thanks

2025-03-13 03:44 UTC, govardhnn commented
> This looks good. Do you plan on adding testing?
> 
> Also, you are out of sync with mavis and fsl subrepos. I believe you're replacing them in your PR with older revisions. Please fix that.

She replacement policies have been tested on Spatra: `sparta/test/cache/simple_cache/DL1.hpp` and this PR only borrows them into Olympia, I have not added any tests. But please let me know if I need to, I will add them.

I have also fixed the `mavis` and `fsl` submodule versions, there are no changes on those repositories now. Thanks!

2025-03-14 15:50 UTC, klingaard approved these changes

2025-03-23 15:32 UTC, merged